name: Github actions ITHS 2023
on: [push]
jobs:
  Explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "The job was triggered on ${{github.event_name}}"
      - run: echo "The branch was ${{github.ref}}"
      - run: echo "The os this was run on is ${{runner.os}}"
      - run: env
  Explore-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
      - name: Build with Maven
        run: mvn -B package --file bank-system/pom.xml
